import { Container } from '@chakra-ui/layout'

import Head from 'next/head'
import { sanityClient } from '../../sanity'
import styles from '../../styles/Home.module.css'
import { Post } from '../../type'

import { BlogCard } from './BlogPost'

import { Box ,Flex } from '@chakra-ui/react'

interface Props {
  posts: Post[];
}

const Home: React.FC<Props> = ({ posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next-Chakra-blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth={'8xl'}>

      </Container>
      <Box
      maxW='7xl'
      display="flex"
      flexDirection='row'
      justifyContent='center'
      alignItems='center'
      flexWrap='wrap'
      gap={8}
      margin={10}
      >
        {posts.map((p) => {
          return (
            <Box display={'flex'} flexDirection="row" key={p._id}>
              <BlogCard post={p} />
            </Box>)
        })}
         {posts.map((p) => {
          return (
            <Box display={'flex'} flexDirection="row" key={p._id}>
              <BlogCard post={p} />
            </Box>)
        })}
        </Box>
    </div>
  )
}
export default Home

export async function getServerSideProps() {
  const query = `*[_type == "post"] { 
   _id,
    _createdAt,
    title,
    author -> {
      name,
      image
    },
    "comments": *[
      _type == "comment" &&
      post._ref == ^._id && 
      approved == true
    ],
    "categories": categories[]->title,
    description,
    mainImage,
    slug,
    body
}`;

  const posts = await sanityClient.fetch(query);
  return {
    props: { posts },
  };
}
