import { Container } from '@chakra-ui/layout'

import Head from 'next/head'
import { sanityClient } from '../../sanity'
import styles from '../../styles/Home.module.css'
import { Post } from '../../type'
import { BlogCard } from '../components/BlogCard'
import ArticleList from '../components/BlogPost'
import Header from '../components/Header'


interface Props {
  posts: Post[];
}

const Home: React.FC<Props> = ({ posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth={'8xl'}>
        <Header />

      </Container>
      <div>
        {posts.map((p) => { return (<ArticleList post={p} key={p._id} />) })}
        {/* {posts.map((p) => { return (<BlogCard post={p} key={p._id} />) })} */}
      </div>

    </div>
  )
}

export default Home


export async function getServerSideProps() {
  const query = `*[_type == "post"] { 
   _id,
    _createdAt,
    title,
    author -> {
      name,
      image
    },
    "comments": *[
      _type == "comment" &&
      post._ref == ^._id && 
      approved == true
    ],
    "categories": categories[]->title,
    description,
    mainImage,
    slug,
    body
}`;

  const posts = await sanityClient.fetch(query);

  return {
    props: { posts },
  };
}
